services:
  postgres:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: jobbotuser
      POSTGRES_PASSWORD: jobbotpass
      POSTGRES_DB: jobbot
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
